### ISSUE TITLE
License compability

### ISSUE THREAD

**Issue by navrozashvili** [k0rventen/avea#17]
Hello

I couldn't find any other way of getting in touch with you so apologies for opening issue.

First of all, thank you for this project. Documentation provided helps a lot. 

Since android app is broken and all the integrations for avea are either written for a specific home automation framework or a os-specific library I decided to fix and extend the functionality of https://github.com/szeged/servo/tree/gh-pages/demos/elgato and host it with github pages as a static page. It is using web bluetooth which works with basically anything that runs chromium. I can do this using documentation you provide in this repo and replicate some of this library's functionality. MIT license lets me do it but project I am extending is licensed under MPL 2. I am not really familiar with licensing so if you don't mind I'd like to have your input on this please. 

Thanks in advance.

**Comment by k0rventen** [comment]
Hi ! 

Glad my documentation helped ! If you have any questions about the code feel free to reach out !

I'm not that much knowledgeable when it comes to license, but from what I found, MIT seems to allow sub licensing, meaning you would be able to take some of my code and include it in another project licensed differently.

And if I'm not mistaken, it would not be a copy of the code but a re-implementation in another language ?

If so, it would make it a "derivative" of my work, which is allowed as part of the MIT License. So you're good to go !

**Comment by navrozashvili** [comment]
Thank you!

I've basically reimplemented everything in javascript https://github.com/navrozashvili/navrozashvili.github.io . I just have to add frontend functionality for it and then maybe do something similar to set_smooth_transition or color patterns.

**Comment by navrozashvili** [comment]
I will be closing issue.

**Comment by navrozashvili** [comment]
Hi mind if I reopen this issue? When I set color and then turn the bulb off it doesn't save the latest color set, it reverts back to previous. Do I need to send a special command for it?

**Comment by k0rventen** [comment]
Hi,

that's weird, I do not have this issue using avea. @pattyland ca you confirm the behaviour ? 

Just as a troubleshoot mesure could you try sending the request twice ?

**Comment by navrozashvili** [comment]
No it's same after setting it twice. Maybe its my command that causes it, mind trying setting color from my website? 
btw avea app works on android 11 now, seems they changed some ble stuff in android 10 which broke apps functionality
