### ISSUE TITLE
Implement firmware version

### ISSUE THREAD

**Issue by pattyland** [k0rventen/avea#8]
Would be nice to get the firmware version of a bulb

**Comment by k0rventen** [comment]
Yup, would be nice but I haven't searched the payload to use so that the bulb sends its version back. I'll try it with #7 next week. 

I'm keeping it opened as well until I have the time to do some reverse engineering, we'll see.

Thx for the continuous improvements ;)

**Comment by k0rventen** [comment]
Hey,

I was able to do some testing this weekend, but unfortunately I couldn't find any field related to the version of the bulb, and as the information is probably encoded in weird ways like the other fields, it's quite difficult to navigate through the requests.

Maybe the original reverse engineer author for the avea bulb might have more information on that (https://github.com/Marmelatze/avea_bulb). Or if another implementation retrieves the firmware version i will implement it on this one !

I'll close up the issue for now, but if you have any news about this topic just reopen it ;)

**Comment by pattyland** [comment]
Hey,

thanks for your work! I think you don't need to look into cryptic payloads for device information, using https://github.com/jnross/Bluetility I can get the firmware and the serial number via the "Device Informatio" tab:

![IMG_2235](https://user-images.githubusercontent.com/838758/85952308-a12c6500-b968-11ea-8b9d-1518ca2cae11.png)
![Bildschirmfoto 2020-06-28 um 17 55 49](https://user-images.githubusercontent.com/838758/85952310-a38ebf00-b968-11ea-8c68-46a8f9e69bec.png)

I think this might help for #7 too?

Greets,
Sören
